# Generated by Django 5.1 on 2024-10-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaitParameter',
            fields=[
                ('gait_parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('measurement_time', models.DateTimeField(auto_now_add=True)),
                ('video_name', models.CharField(max_length=255)),
                ('json_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('average_step_time', models.FloatField()),
                ('average_stride_length', models.FloatField()),
                ('movement_speed', models.FloatField()),
                ('stance', models.FloatField()),
                ('health_value', models.FloatField()),
                ('each_of_step_length', models.FloatField()),
                ('y_values', models.JSONField()),
                ('left_y_value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_id', models.IntegerField()),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('gait_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton_analysis.gaitparameter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton_analysis.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='IssueAndSuggestion',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_name', models.CharField(max_length=255)),
                ('suggestion', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton_analysis.historyrecord')),
            ],
        ),
    ]
